// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzroF5dD49xOFnOJD0IdTVFi84sihRAXc',
    appId: '1:563694934248:web:77ac79d7d5c7b96357515d',
    messagingSenderId: '563694934248',
    projectId: 'my-test-project-af16e',
    authDomain: 'my-test-project-af16e.firebaseapp.com',
    storageBucket: 'my-test-project-af16e.firebasestorage.app',
    measurementId: 'G-QZTQ3KZGFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnG_qYdSJoLRfXnImFLgQR9Yq3Xzqzk6I',
    appId: '1:563694934248:android:44b93cad0aef26c057515d',
    messagingSenderId: '563694934248',
    projectId: 'my-test-project-af16e',
    storageBucket: 'my-test-project-af16e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqsV9pTc6RfcAjuvwljs5PLSs0dk0LP8',
    appId: '1:563694934248:ios:6831f5b333b105f257515d',
    messagingSenderId: '563694934248',
    projectId: 'my-test-project-af16e',
    storageBucket: 'my-test-project-af16e.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSqsV9pTc6RfcAjuvwljs5PLSs0dk0LP8',
    appId: '1:563694934248:ios:6831f5b333b105f257515d',
    messagingSenderId: '563694934248',
    projectId: 'my-test-project-af16e',
    storageBucket: 'my-test-project-af16e.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzroF5dD49xOFnOJD0IdTVFi84sihRAXc',
    appId: '1:563694934248:web:39c1a77513e712f057515d',
    messagingSenderId: '563694934248',
    projectId: 'my-test-project-af16e',
    authDomain: 'my-test-project-af16e.firebaseapp.com',
    storageBucket: 'my-test-project-af16e.firebasestorage.app',
    measurementId: 'G-GN5XMFF0EH',
  );
}
